# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171116_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20),
        ),
    ]
